/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package culturest;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jesus
 */
public class convertidor extends javax.swing.JFrame {

    /**
     * Creates new form convertidor
     */
    public convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        json = new javax.swing.JButton();
        xml = new javax.swing.JButton();
        csv = new javax.swing.JButton();
        sql = new javax.swing.JButton();
        archivo = new javax.swing.JButton();
        salir2 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        back.setText("Atras");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 70, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Convertir Archivo en java");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        json.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        json.setText("JSON");
        getContentPane().add(json, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        xml.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xml.setText("XML");
        getContentPane().add(xml, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        csv.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        csv.setText("CSV");
        csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvActionPerformed(evt);
            }
        });
        getContentPane().add(csv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        sql.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sql.setText("SQL");
        getContentPane().add(sql, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        archivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        archivo.setText("Seleccionar Archivo");
        archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoActionPerformed(evt);
            }
        });
        getContentPane().add(archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 200, 40));

        salir2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salir2.setText("Salir");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 70, 40));
        getContentPane().add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 500, 320));

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        index ventana = new index();
        ventana.setVisible(true);// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoActionPerformed


    }//GEN-LAST:event_archivoActionPerformed

    private void csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvActionPerformed
    
        
        try (BufferedReader reader = new BufferedReader(new FileReader("document"));
             BufferedWriter writer = new BufferedWriter(new FileWriter("archivo.csv"))) {

            String linea;
            while ((linea = reader.readLine()) != null) {
                // Reemplazar los espacios en blanco con comas
                linea = linea.trim().replace(" ", ",");
                // Escribir la línea en el archivo CSV
                writer.write(linea + "\n");
            }

            System.out.println("Archivo CSV generado correctamente.");
        } catch (IOException ex) {
            ex.printStackTrace();
        }

            // TODO add your handling code here:
    }//GEN-LAST:event_csvActionPerformed

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
       System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_salir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archivo;
    private javax.swing.JButton back;
    private javax.swing.JButton csv;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton json;
    private javax.swing.JButton salir2;
    private javax.swing.JButton sql;
    private javax.swing.JButton xml;
    // End of variables declaration//GEN-END:variables
}
